name: sharp-daggers
channels:
- defaults
dependencies:
- appnope=0.1.2
- backcall=0.2.0
- ca-certificates=2021.10.26
- certifi=2021.10.8
- decorator=5.1.0
- ipython=7.29.0
- jedi=0.18.0
- libcxx=12.0.0
- libffi=3.3
- matplotlib-inline=0.1.2
- ncurses=6.3
- openssl=1.1.1l
- parso=0.8.2
- pexpect=4.8.0
- pickleshare=0.7.5
- pip=21.2.4
- prompt-toolkit=3.0.20
- ptyprocess=0.7.0
- pygments=2.10.0
- python=3.8.12
- readline=8.1
- setuptools=58.0.4
- sqlite=3.37.0
- tk=8.6.11
- traitlets=5.1.1
- wcwidth=0.2.5
- wheel=0.37.0
- xz=5.2.5
- zlib=1.2.11
- pip:
  - black==21.12b0
  - cffi==1.15.0
  - charset-normalizer==2.0.9
  - click==8.0.3
  - cloudpickle==2.0.0
  - cycler==0.11.0
  - cython==0.29.26
  - fasteners==0.15
  - fonttools==4.28.5
  - free-mujoco-py==2.1.6
  - glfw==1.12.0
  - gym==0.21.0
  - idna==3.3
  - imageio==2.13.5
  - isort==5.10.1
  - kiwisolver==1.3.2
  - llvmlite==0.36.0
  - matplotlib==3.5.1
  - monotonic==1.6
  - mujoco-py==2.1.2.14
  - mypy-extensions==0.4.3
  - numba==0.53.1
  - numpy==1.21.5
  - packaging==21.3
  - pathspec==0.9.0
  - pillow==8.4.0
  - platformdirs==2.4.0
  - pycparser==2.21
  - pyparsing==3.0.6
  - python-dateutil==2.8.2
  - pyyaml==6.0
  - requests==2.26.0
  - robosuite==1.3.1
  - scipy==1.7.3
  - six==1.16.0
  - tomli==1.2.3
  - typing-extensions==4.0.1
  - urllib3==1.26.7
